service: serverless-rekognition

plugins:
  - serverless-offline
  - serverless-plugin-custom-binary

custom:
  apigatewayBinary:
    types:
      - 'image/png'
      - 'image/jpeg'

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: GET
      - http: 
          path: /{proxy+}
          method: ANY
          contentHandling: CONVERT_TO_BINARY